; ==============================
; SOCKET (fix no such file bug)
; ==============================

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700


; ==============================
; WEB UI
; ==============================

[inet_http_server]
port=0.0.0.0:9001
username=admin
password=Admin123


; ==============================
; CORE
; ==============================

[supervisord]
logfile=/var/log/supervisord.log
pidfile=/tmp/supervisord.pid
nodaemon=false


; ==============================
; RPC
; ==============================

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface


; ==============================
; SUPERVISORCTL
; ==============================

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock


; ==============================
; PROGRAMS
; ==============================

[program:srs_recording]
command=/home/ai/projects/venv/bin/python -m srs.recording
directory=/home/ai/projects/srs
environment=PYTHONPATH="/home/ai/projects/srs/src"
user=ai
autostart=true
autorestart=true
stdout_logfile=/home/ai/logs/srs_recording.out.log
stderr_logfile=/home/ai/logs/srs_recording.err.log


[program:srs_forward_video]
command=/home/ai/projects/venv/bin/python -m srs.forward_video
directory=/home/ai/projects/srs
environment=PYTHONPATH="/home/ai/projects/srs/src"
user=ai
autostart=true
autorestart=true
stdout_logfile=/home/ai/logs/srs_forward_video.out.log
stderr_logfile=/home/ai/logs/srs_forward_video.err.log